export const ADMIN_DASHBOARD_DETAILS_REQUEST =
  "ADMIN_DASHBOARD_DETAILS_REQUEST";
export const ADMIN_DASHBOARD_DETAILS_SUCCESS =
  "ADMIN_DASHBOARD_DETAILS_SUCCESS";
export const ADMIN_DASHBOARD_DETAILS_FAIL = "ADMIN_DASHBOARD_DETAILS_FAIL";
