export const EMPLOYEE_REGISTER_REQUEST = "EMPLOYEE_REGISTER_REQUEST";
export const EMPLOYEE_REGISTER_SUCCESS = "EMPLOYEE_REGISTER_SUCCESS";
export const EMPLOYEE_REGISTER_FAIL = "EMPLOYEE_REGISTER_FAIL";

export const EMPLOYEE_LOGIN_REQUEST = "EMPLOYEE_LOGIN_REQUEST";
export const EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS";
export const EMPLOYEE_LOGIN_FAIL = "EMPLOYEE_LOGIN_FAIL";
export const EMPLOYEE_LOGOUT = "EMPLOYEE_LOGOUT";
