export const EMPLOYEE_REGISTER_REQUEST = "EMPLOYEE_REGISTER_REQUEST";
export const EMPLOYEE_REGISTER_SUCCESS = "EMPLOYEE_REGISTER_SUCCESS";
export const EMPLOYEE_REGISTER_FAIL = "EMPLOYEE_REGISTER_FAIL";

export const EMPLOYEE_LOGIN_REQUEST = "EMPLOYEE_LOGIN_REQUEST";
export const EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS";
export const EMPLOYEE_LOGIN_FAIL = "EMPLOYEE_LOGIN_FAIL";
export const EMPLOYEE_LOGOUT = "EMPLOYEE_LOGOUT";

export const EMPLOYEE_PRODUCT_ORDERS_DETAILS_REQUEST =
  "EMPLOYEE_PRODUCT_ORDERS_DETAILS_REQUEST";
export const EMPLOYEE_PRODUCT_ORDERS_DETAILS_SUCCESS =
  "EMPLOYEE_PRODUCT_ORDERS_DETAILS_SUCCESS";
export const EMPLOYEE_PRODUCT_ORDERS_DETAILS_FAIL =
  "EMPLOYEE_PRODUCT_ORDERS_DETAILS_FAIL";

export const EMPLOYEE_CUSTOMERS_DETAILS_REQUEST =
  "EMPLOYEE_CUSTOMERS_DETAILS_REQUEST";
export const EMPLOYEE_CUSTOMERS_DETAILS_SUCCESS =
  "EMPLOYEE_CUSTOMERS_DETAILS_SUCCESS";
export const EMPLOYEE_CUSTOMERS_DETAILS_FAIL =
  "EMPLOYEE_CUSTOMERS_DETAILS_FAIL";
