export const TAILOR_LOGIN_REQUEST = "TAILOR_LOGIN_REQUEST";
export const TAILOR_LOGIN_SUCCESS = "TAILOR_LOGIN_SUCCESS";
export const TAILOR_LOGIN_FAIL = "TAILOR_LOGIN_FAIL";
export const TAILOR_LOGOUT = "TAILOR_LOGOUT";

export const TAILOR_REGISTER_REQUEST = "TAILOR_REGISTER_REQUEST";
export const TAILOR_REGISTER_SUCCESS = "TAILOR_REGISTER_SUCCESS";
export const TAILOR_REGISTER_FAIL = "TAILOR_REGISTER_FAIL";

export const TAILOR_SALES_DETAILS_REQUEST = "TAILOR_SALES_DETAILS_REQUEST";
export const TAILOR_SALES_DETAILS_SUCCESS = "TAILOR_SALES_DETAILS_SUCCESS";
export const TAILOR_SALES_DETAILS_FAIL = "TAILOR_SALES_DETAILS_FAIL";

export const TAILOR_ORDERS_DETAILS_REQUEST = "TAILOR_ORDERS_DETAILS_REQUEST";
export const TAILOR_ORDERS_DETAILS_SUCCESS = "TAILOR_ORDERS_DETAILS_SUCCESS";
export const TAILOR_ORDERS_DETAILS_FAIL = "TAILOR_ORDERS_DETAILS_FAIL";
