export const TAILOR_LOGIN_REQUEST = "TAILOR_LOGIN_REQUEST";
export const TAILOR_LOGIN_SUCCESS = "TAILOR_LOGIN_SUCCESS";
export const TAILOR_LOGIN_FAIL = "TAILOR_LOGIN_FAIL";
export const TAILOR_LOGOUT = "TAILOR_LOGOUT";
